# Generated by Django 4.0.4 on 2022-05-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_result_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='approved',
        ),
        migrations.AddField(
            model_name='problem',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
