# Generated by Django 4.0.4 on 2022-05-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='module_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
