# Generated by Django 4.0.4 on 2022-05-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacher_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='module_name',
        ),
    ]
