# Generated by Django 4.0.4 on 2022-05-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_administrator_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='module_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
