# Generated by Django 4.0.4 on 2022-05-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_teacher_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
